name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Checkout code
        uses: actions/checkout@v2

      - name: List directory contents
        run: ls -la

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with code coverage
        run: pytest --cov-report=html:coverage_re --cov=app --cov=form_checks tests/
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

      - name: Analysing the code with pylint
        run: |
          find . -name '*.py' -exec pylint {} \;
