name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Checkout code
        uses: actions/checkout@v2

      - name: List directory contents
        run: ls -la

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with code coverage
        run: pytest

      - name: Deploy to PythonAnywhere
        run: |
          pip install pythonanywhere
          pa_autoconfigure_web.py --python=python3.11 timotej.pythonanywhere.com

      - name: Push code to PythonAnywhere
        run: |
          git push https://timotej@git.pythonanywhere.com/timotej/timotej.pythonanywhere.com.git HEAD:master

      - name: Reload webapp
        uses: jensvog/pythonanywhere-webapp-reload-action@v1
        with:
          host: 'www.pythonanywhere.com'
          username: timotej
          api-token: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
          domain-name: timotej.pythonanywhere.com
